package id.atiila.losmuf;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataNasabah implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Cabang Asal")
	private java.lang.String cbgAsal;

	@org.kie.api.definition.type.Label("Approval Level")
	private java.lang.Integer aprLevel;

	@org.kie.api.definition.type.Label("Approval Function")
	private java.lang.String aprFunction;

	@org.kie.api.definition.type.Label("Approval Plafond")
	private java.lang.String aprPlafond;

	@org.kie.api.definition.type.Label("Jumlah Overdue Sebelumnya")
	private java.lang.Integer ovdSebelum;

	@org.kie.api.definition.type.Label("Usia Kendaraan")
	private java.lang.Integer usiaKend;

	@org.kie.api.definition.type.Label("Jenis Indentitas")
	private java.util.List<java.lang.String> jnsIndentitas;

	@org.kie.api.definition.type.Label("Nama Debitur")
	private java.lang.String namaDebitur;

	@org.kie.api.definition.type.Label("Approval Result")
	private java.util.List<java.lang.String> aprResult;

	@org.kie.api.definition.type.Label("Approval Function Rating")
	private java.util.List<java.lang.String> aprFunctionRating;

	@org.kie.api.definition.type.Label("Status Pengajuan Aplikasi Sebelumnya")
	private java.util.List<java.lang.String> stsAplikasiSebelum;

	@org.kie.api.definition.type.Label("Status Kontrak")
	private java.util.List<java.lang.String> stsKontrak;

	@org.kie.api.definition.type.Label("Jenis Pembiayaan")
	private java.util.List<java.lang.String> jnsPembiayaan;

	@org.kie.api.definition.type.Label("Portofolio")
	private java.util.List<java.lang.String> portofolio;

	@org.kie.api.definition.type.Label("Cara Pembayaran Angsuran")
	private java.util.List<java.lang.String> caraBayarAngs;

	@org.kie.api.definition.type.Label("Channel Rating")
	private java.util.List<java.lang.String> channelRating;

	@org.kie.api.definition.type.Label("Sales Officer Rating")
	private java.util.List<java.lang.String> salesOfficeRating;

	@org.kie.api.definition.type.Label("Jenis Sumber Nasabah")
	private java.util.List<java.lang.String> jnsSumberNsbh;

	@org.kie.api.definition.type.Label("Object Kendaraan")
	private java.util.List<java.lang.String> objKend;

	@org.kie.api.definition.type.Label("Tipe Kendaraan")
	private java.util.List<java.lang.String> tipeKend;

	@org.kie.api.definition.type.Label("Merk Kendaraan")
	private String merkKend;

	@org.kie.api.definition.type.Label("Kategori Kendaraan")
	private java.util.List<java.lang.String> kategoriKend;

	@org.kie.api.definition.type.Label("Usia Debitur")
	private java.lang.Integer usiaDebitur;

	@org.kie.api.definition.type.Label("Pekerjaan Debitur")
	private java.lang.String kerjaDebitur;

	@org.kie.api.definition.type.Label("Lama Bekerja Debitur")
	private java.lang.Integer lamaKerja;

	@org.kie.api.definition.type.Label("Jenis Nasabah")
	private java.util.List<java.lang.String> jnsNasabah;

	@org.kie.api.definition.type.Label("Jumlah Tanggungan")
	private java.lang.Integer jmlhTanggungan;

	@org.kie.api.definition.type.Label("Status Pernikahan")
	private java.util.List<java.lang.String> stsPernikahan;

	@org.kie.api.definition.type.Label("Lama Tinggal Debitur")
	private java.lang.Integer lamaTinggal;

	@org.kie.api.definition.type.Label("Status Kepemilikan Rumah")
	private java.util.List<java.lang.String> stsPemilikanRumah;

	@org.kie.api.definition.type.Label("Daya Listrik Pada Rumah Tinggal")
	private java.lang.Integer dayaListrik;

	@org.kie.api.definition.type.Label("Tipe Jalan Rumah Tinggal")
	private java.lang.String tipeJlnRumah;

	@org.kie.api.definition.type.Label("Nilai Debt Service Ratio")
	private java.lang.Integer nilDebtServiceRatio;

	@org.kie.api.definition.type.Label("Nilai Debt Income Ratio")
	private java.lang.Integer nilDebtIncomeRatio;

	@org.kie.api.definition.type.Label("Pokok Hutang")
	private java.lang.Integer pokHutang;

	@org.kie.api.definition.type.Label("Tenor Kredit")
	private java.lang.Integer tenorKredit;

	@org.kie.api.definition.type.Label("Amount Down Payment")
	private java.lang.Integer amountDP;

	@org.kie.api.definition.type.Label("Installment Type")
	private java.util.List<java.lang.String> installmentType;

	@org.kie.api.definition.type.Label("Credit Scheme")
	private java.lang.String creditScheme;

	@org.kie.api.definition.type.Label("Total Unit Kendaraan")
	private java.lang.Integer totalUnitKend;

	@org.kie.api.definition.type.Label(value = "Skor Mobil Pernikahan Pemilikan Rumah")
	private java.lang.Integer skorMobilPernikahanPemilikanRumah;

	@org.kie.api.definition.type.Label(value = "Skor Mobil Lama Kerja")
	private java.lang.Integer skorMobilLamaKerja;

	@org.kie.api.definition.type.Label(value = "Skor Mobil Kerja Debitur Usia Kendaraan")
	private java.lang.Integer skorMobilKerjaDebiturUsiaKendaraan;

	public DataNasabah() {
	}

	public java.lang.String getCbgAsal() {
		return this.cbgAsal;
	}

	public void setCbgAsal(java.lang.String cbgAsal) {
		this.cbgAsal = cbgAsal;
	}

	public java.lang.Integer getAprLevel() {
		return this.aprLevel;
	}

	public void setAprLevel(java.lang.Integer aprLevel) {
		this.aprLevel = aprLevel;
	}

	public java.lang.String getAprFunction() {
		return this.aprFunction;
	}

	public void setAprFunction(java.lang.String aprFunction) {
		this.aprFunction = aprFunction;
	}

	public java.lang.String getAprPlafond() {
		return this.aprPlafond;
	}

	public void setAprPlafond(java.lang.String aprPlafond) {
		this.aprPlafond = aprPlafond;
	}

	public java.lang.Integer getOvdSebelum() {
		return this.ovdSebelum;
	}

	public void setOvdSebelum(java.lang.Integer ovdSebelum) {
		this.ovdSebelum = ovdSebelum;
	}

	public java.lang.Integer getUsiaKend() {
		return this.usiaKend;
	}

	public void setUsiaKend(java.lang.Integer usiaKend) {
		this.usiaKend = usiaKend;
	}

	public java.util.List<java.lang.String> getJnsIndentitas() {
		return this.jnsIndentitas;
	}

	public void setJnsIndentitas(java.util.List<java.lang.String> jnsIndentitas) {
		this.jnsIndentitas = jnsIndentitas;
	}

	public java.lang.String getNamaDebitur() {
		return this.namaDebitur;
	}

	public void setNamaDebitur(java.lang.String namaDebitur) {
		this.namaDebitur = namaDebitur;
	}

	public java.util.List<java.lang.String> getAprResult() {
		return this.aprResult;
	}

	public void setAprResult(java.util.List<java.lang.String> aprResult) {
		this.aprResult = aprResult;
	}

	public java.util.List<java.lang.String> getAprFunctionRating() {
		return this.aprFunctionRating;
	}

	public void setAprFunctionRating(
			java.util.List<java.lang.String> aprFunctionRating) {
		this.aprFunctionRating = aprFunctionRating;
	}

	public java.util.List<java.lang.String> getStsAplikasiSebelum() {
		return this.stsAplikasiSebelum;
	}

	public void setStsAplikasiSebelum(
			java.util.List<java.lang.String> stsAplikasiSebelum) {
		this.stsAplikasiSebelum = stsAplikasiSebelum;
	}

	public java.util.List<java.lang.String> getStsKontrak() {
		return this.stsKontrak;
	}

	public void setStsKontrak(java.util.List<java.lang.String> stsKontrak) {
		this.stsKontrak = stsKontrak;
	}

	public java.util.List<java.lang.String> getJnsPembiayaan() {
		return this.jnsPembiayaan;
	}

	public void setJnsPembiayaan(java.util.List<java.lang.String> jnsPembiayaan) {
		this.jnsPembiayaan = jnsPembiayaan;
	}

	public java.util.List<java.lang.String> getPortofolio() {
		return this.portofolio;
	}

	public void setPortofolio(java.util.List<java.lang.String> portofolio) {
		this.portofolio = portofolio;
	}

	public java.util.List<java.lang.String> getCaraBayarAngs() {
		return this.caraBayarAngs;
	}

	public void setCaraBayarAngs(java.util.List<java.lang.String> caraBayarAngs) {
		this.caraBayarAngs = caraBayarAngs;
	}

	public java.util.List<java.lang.String> getChannelRating() {
		return this.channelRating;
	}

	public void setChannelRating(java.util.List<java.lang.String> channelRating) {
		this.channelRating = channelRating;
	}

	public java.util.List<java.lang.String> getSalesOfficeRating() {
		return this.salesOfficeRating;
	}

	public void setSalesOfficeRating(
			java.util.List<java.lang.String> salesOfficeRating) {
		this.salesOfficeRating = salesOfficeRating;
	}

	public java.util.List<java.lang.String> getJnsSumberNsbh() {
		return this.jnsSumberNsbh;
	}

	public void setJnsSumberNsbh(java.util.List<java.lang.String> jnsSumberNsbh) {
		this.jnsSumberNsbh = jnsSumberNsbh;
	}

	public java.util.List<java.lang.String> getObjKend() {
		return this.objKend;
	}

	public void setObjKend(java.util.List<java.lang.String> objKend) {
		this.objKend = objKend;
	}

	public java.util.List<java.lang.String> getTipeKend() {
		return this.tipeKend;
	}

	public void setTipeKend(java.util.List<java.lang.String> tipeKend) {
		this.tipeKend = tipeKend;
	}

	public java.util.List<java.lang.String> getKategoriKend() {
		return this.kategoriKend;
	}

	public void setKategoriKend(java.util.List<java.lang.String> kategoriKend) {
		this.kategoriKend = kategoriKend;
	}

	public java.lang.String getMerkKend() {
		return this.merkKend;
	}

	public void setMerkKend(java.lang.String merkKend) {
		this.merkKend = merkKend;
	}

	public java.lang.Integer getUsiaDebitur() {
		return this.usiaDebitur;
	}

	public void setUsiaDebitur(java.lang.Integer usiaDebitur) {
		this.usiaDebitur = usiaDebitur;
	}

	public java.lang.String getKerjaDebitur() {
		return this.kerjaDebitur;
	}

	public void setKerjaDebitur(java.lang.String kerjaDebitur) {
		this.kerjaDebitur = kerjaDebitur;
	}

	public java.lang.Integer getLamaKerja() {
		return this.lamaKerja;
	}

	public void setLamaKerja(java.lang.Integer lamaKerja) {
		this.lamaKerja = lamaKerja;
	}

	public java.util.List<java.lang.String> getJnsNasabah() {
		return this.jnsNasabah;
	}

	public void setJnsNasabah(java.util.List<java.lang.String> jnsNasabah) {
		this.jnsNasabah = jnsNasabah;
	}

	public java.lang.Integer getJmlhTanggungan() {
		return this.jmlhTanggungan;
	}

	public void setJmlhTanggungan(java.lang.Integer jmlhTanggungan) {
		this.jmlhTanggungan = jmlhTanggungan;
	}

	public java.util.List<java.lang.String> getStsPernikahan() {
		return this.stsPernikahan;
	}

	public void setStsPernikahan(java.util.List<java.lang.String> stsPernikahan) {
		this.stsPernikahan = stsPernikahan;
	}

	public java.lang.Integer getLamaTinggal() {
		return this.lamaTinggal;
	}

	public void setLamaTinggal(java.lang.Integer lamaTinggal) {
		this.lamaTinggal = lamaTinggal;
	}

	public java.util.List<java.lang.String> getStsPemilikanRumah() {
		return this.stsPemilikanRumah;
	}

	public void setStsPemilikanRumah(
			java.util.List<java.lang.String> stsPemilikanRumah) {
		this.stsPemilikanRumah = stsPemilikanRumah;
	}

	public java.lang.Integer getDayaListrik() {
		return this.dayaListrik;
	}

	public void setDayaListrik(java.lang.Integer dayaListrik) {
		this.dayaListrik = dayaListrik;
	}

	public java.lang.String getTipeJlnRumah() {
		return this.tipeJlnRumah;
	}

	public void setTipeJlnRumah(java.lang.String tipeJlnRumah) {
		this.tipeJlnRumah = tipeJlnRumah;
	}

	public java.lang.Integer getNilDebtServiceRatio() {
		return this.nilDebtServiceRatio;
	}

	public void setNilDebtServiceRatio(java.lang.Integer nilDebtServiceRatio) {
		this.nilDebtServiceRatio = nilDebtServiceRatio;
	}

	public java.lang.Integer getNilDebtIncomeRatio() {
		return this.nilDebtIncomeRatio;
	}

	public void setNilDebtIncomeRatio(java.lang.Integer nilDebtIncomeRatio) {
		this.nilDebtIncomeRatio = nilDebtIncomeRatio;
	}

	public java.lang.Integer getPokHutang() {
		return this.pokHutang;
	}

	public void setPokHutang(java.lang.Integer pokHutang) {
		this.pokHutang = pokHutang;
	}

	public java.lang.Integer getTenorKredit() {
		return this.tenorKredit;
	}

	public void setTenorKredit(java.lang.Integer tenorKredit) {
		this.tenorKredit = tenorKredit;
	}

	public java.lang.Integer getAmountDP() {
		return this.amountDP;
	}

	public void setAmountDP(java.lang.Integer amountDP) {
		this.amountDP = amountDP;
	}

	public java.util.List<java.lang.String> getInstallmentType() {
		return this.installmentType;
	}

	public void setInstallmentType(
			java.util.List<java.lang.String> installmentType) {
		this.installmentType = installmentType;
	}

	public java.lang.String getCreditScheme() {
		return this.creditScheme;
	}

	public void setCreditScheme(java.lang.String creditScheme) {
		this.creditScheme = creditScheme;
	}

	public java.lang.Integer getTotalUnitKend() {
		return this.totalUnitKend;
	}

	public void setTotalUnitKend(java.lang.Integer totalUnitKend) {
		this.totalUnitKend = totalUnitKend;
	}

	public java.lang.Integer getSkorMobilPernikahanPemilikanRumah() {
		return this.skorMobilPernikahanPemilikanRumah;
	}

	public void setSkorMobilPernikahanPemilikanRumah(
			java.lang.Integer skorMobilPernikahanPemilikanRumah) {
		this.skorMobilPernikahanPemilikanRumah = skorMobilPernikahanPemilikanRumah;
	}

	public java.lang.Integer getSkorMobilLamaKerja() {
		return this.skorMobilLamaKerja;
	}

	public void setSkorMobilLamaKerja(java.lang.Integer skorMobilLamaKerja) {
		this.skorMobilLamaKerja = skorMobilLamaKerja;
	}

	public java.lang.Integer getSkorMobilKerjaDebiturUsiaKendaraan() {
		return this.skorMobilKerjaDebiturUsiaKendaraan;
	}

	public void setSkorMobilKerjaDebiturUsiaKendaraan(
			java.lang.Integer skorMobilKerjaDebiturUsiaKendaraan) {
		this.skorMobilKerjaDebiturUsiaKendaraan = skorMobilKerjaDebiturUsiaKendaraan;
	}

	public DataNasabah(java.lang.String cbgAsal, java.lang.Integer aprLevel,
			java.lang.String aprFunction, java.lang.String aprPlafond,
			java.lang.Integer ovdSebelum, java.lang.Integer usiaKend,
			java.util.List<java.lang.String> jnsIndentitas,
			java.lang.String namaDebitur,
			java.util.List<java.lang.String> aprResult,
			java.util.List<java.lang.String> aprFunctionRating,
			java.util.List<java.lang.String> stsAplikasiSebelum,
			java.util.List<java.lang.String> stsKontrak,
			java.util.List<java.lang.String> jnsPembiayaan,
			java.util.List<java.lang.String> portofolio,
			java.util.List<java.lang.String> caraBayarAngs,
			java.util.List<java.lang.String> channelRating,
			java.util.List<java.lang.String> salesOfficeRating,
			java.util.List<java.lang.String> jnsSumberNsbh,
			java.util.List<java.lang.String> objKend,
			java.util.List<java.lang.String> tipeKend,
			java.lang.String merkKend,
			java.util.List<java.lang.String> kategoriKend,
			java.lang.Integer usiaDebitur, java.lang.String kerjaDebitur,
			java.lang.Integer lamaKerja,
			java.util.List<java.lang.String> jnsNasabah,
			java.lang.Integer jmlhTanggungan,
			java.util.List<java.lang.String> stsPernikahan,
			java.lang.Integer lamaTinggal,
			java.util.List<java.lang.String> stsPemilikanRumah,
			java.lang.Integer dayaListrik, java.lang.String tipeJlnRumah,
			java.lang.Integer nilDebtServiceRatio,
			java.lang.Integer nilDebtIncomeRatio, java.lang.Integer pokHutang,
			java.lang.Integer tenorKredit, java.lang.Integer amountDP,
			java.util.List<java.lang.String> installmentType,
			java.lang.String creditScheme, java.lang.Integer totalUnitKend,
			java.lang.Integer skorMobilPernikahanPemilikanRumah,
			java.lang.Integer skorMobilLamaKerja,
			java.lang.Integer skorMobilKerjaDebiturUsiaKendaraan) {
		this.cbgAsal = cbgAsal;
		this.aprLevel = aprLevel;
		this.aprFunction = aprFunction;
		this.aprPlafond = aprPlafond;
		this.ovdSebelum = ovdSebelum;
		this.usiaKend = usiaKend;
		this.jnsIndentitas = jnsIndentitas;
		this.namaDebitur = namaDebitur;
		this.aprResult = aprResult;
		this.aprFunctionRating = aprFunctionRating;
		this.stsAplikasiSebelum = stsAplikasiSebelum;
		this.stsKontrak = stsKontrak;
		this.jnsPembiayaan = jnsPembiayaan;
		this.portofolio = portofolio;
		this.caraBayarAngs = caraBayarAngs;
		this.channelRating = channelRating;
		this.salesOfficeRating = salesOfficeRating;
		this.jnsSumberNsbh = jnsSumberNsbh;
		this.objKend = objKend;
		this.tipeKend = tipeKend;
		this.merkKend = merkKend;
		this.kategoriKend = kategoriKend;
		this.usiaDebitur = usiaDebitur;
		this.kerjaDebitur = kerjaDebitur;
		this.lamaKerja = lamaKerja;
		this.jnsNasabah = jnsNasabah;
		this.jmlhTanggungan = jmlhTanggungan;
		this.stsPernikahan = stsPernikahan;
		this.lamaTinggal = lamaTinggal;
		this.stsPemilikanRumah = stsPemilikanRumah;
		this.dayaListrik = dayaListrik;
		this.tipeJlnRumah = tipeJlnRumah;
		this.nilDebtServiceRatio = nilDebtServiceRatio;
		this.nilDebtIncomeRatio = nilDebtIncomeRatio;
		this.pokHutang = pokHutang;
		this.tenorKredit = tenorKredit;
		this.amountDP = amountDP;
		this.installmentType = installmentType;
		this.creditScheme = creditScheme;
		this.totalUnitKend = totalUnitKend;
		this.skorMobilPernikahanPemilikanRumah = skorMobilPernikahanPemilikanRumah;
		this.skorMobilLamaKerja = skorMobilLamaKerja;
		this.skorMobilKerjaDebiturUsiaKendaraan = skorMobilKerjaDebiturUsiaKendaraan;
	}

}